name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker Buildx 설정 (멀티 아키텍처 빌드를 지원)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Docker 레이어 캐시하기 (빌드 속도 최적화)
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4. GHCR 로그인 (GitHub Container Registry)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}  # GitHub 사용자 이름
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub 제공 토큰

      # 5. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .  # 현재 디렉토리에서 Dockerfile을 사용
          file: ./Dockerfile  # 최상위에 있는 Dockerfile을 사용
          push: true  # 이미지를 푸시
          tags: ghcr.io/${{ github.repository_owner }}/waclanbot:${{ github.sha }}  # GHCR에 푸시할 태그
